package com.enzhongwen.hanyu3
import com.enzhongwen.hanyu3.database.Saved

var currentList = mutableListOf<Saved>()

val vocab_lesson1: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "月",
        pinyin = "yuè",
        definition = R.string.d312,
        id1 = 312,
        stroke1 = R.drawable.yue,
        sound = R.raw.yue4,
    ),
    Saved(
        word = "日",
        pinyin = "rì",
        definition = R.string.d313,
        id1 = 313,
        stroke1 = R.drawable.ri,
        sound = R.raw.ri4,
    ),
    Saved(
        word = "昨天",
        pinyin = "zuótiān",
        definition = R.string.d314,
        id1 = 314,
        stroke1 = R.drawable.zuo6,
        stroke2 = R.drawable.tian,
        sound = R.raw.zuo2tian1,
    ),
    Saved(
        word = "假期",
        pinyin = "jiàqī",
        definition = R.string.d315,
        id1 = 315,
        stroke1 = R.drawable.jia3,
        stroke2 = R.drawable.qi5,
        sound = R.raw.jia4qi1,
    ),
    Saved(
        word = "结束",
        pinyin = "jiéshù",
        definition = R.string.d316,
        id1 = 316,
        stroke1 = R.drawable.jie2,
        stroke2 = R.drawable.shu4,
        sound = R.raw.jie2shu4,
    ),
    Saved(
        word = "开学",
        pinyin = "kāi xué",
        definition = R.string.d317,
        id1 = 317,
        stroke1 = R.drawable.kai,
        stroke2 = R.drawable.xue,
        sound = R.raw.kai1xue2,
    ),
    Saved(
        word = "年",
        pinyin = "nián",
        definition = R.string.d318,
        id1 = 318,
        stroke1 = R.drawable.nian,
        sound = R.raw.nian2,
    ),
    Saved(
        word = "去年",
        pinyin = "qùnián",
        definition = R.string.d319,
        id1 = 319,
        stroke1 = R.drawable.qu,
        stroke2 = R.drawable.nian,
        sound = R.raw.qu4nian2,
    ),
    Saved(
        word = "小学",
        pinyin = "xiǎoxué",
        definition = R.string.d320,
        id1 = 320,
        stroke1 = R.drawable.xiao2,
        stroke2 = R.drawable.xue,
        sound = R.raw.xiao3xue2,
    ),
    Saved(
        word = "学期",
        pinyin = "xuéqī",
        definition = R.string.d321,
        id1 = 321,
        stroke1 = R.drawable.xue,
        stroke2 = R.drawable.qi5,
        sound = R.raw.xue2qi1,
    ),
    Saved(
        word = "发",
        pinyin = "fā",
        definition = R.string.d322,
        id1 = 322,
        stroke1 = R.drawable.fa,
        sound = R.raw.fa1,
    ),
    Saved(
        word = "元旦",
        pinyin = "Yuándàn",
        definition = R.string.d323,
        id1 = 323,
        stroke1 = R.drawable.yuan4,
        stroke2 = R.drawable.dan2,
        sound = R.raw.yuan2dan4,
    ),
    Saved(
        word = "圣诞节",
        pinyin = "Shèngdàn Jié",
        definition = R.string.d324,
        id1 = 324,
        stroke1 = R.drawable.sheng3,
        stroke2 = R.drawable.dan3,
        stroke3 = R.drawable.jie3,
        sound = R.raw.sheng4dan4jie2,
    ),
    Saved(
        word = "国庆节",
        pinyin = "Guóqìng Jié",
        definition = R.string.d325,
        id1 = 325,
        stroke1 = R.drawable.guo2,
        stroke2 = R.drawable.qing,
        stroke3 = R.drawable.jie3,
        sound = R.raw.guo2qing4jie2,
    )

)

val vocab_lesson2: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "星期",
        pinyin = "xīngqī",
        definition = R.string.d326,
        id1 = 326,
        stroke1 = R.drawable.xing4,
        stroke2 = R.drawable.qi5,
        sound = R.raw.xing1qi1,
    ),
    Saved(
        word = "星期一",
        pinyin = "xīngqīyī",
        definition = R.string.d327,
        id1 = 327,
        stroke1 = R.drawable.xing4,
        stroke2 = R.drawable.qi5,
        stroke3 = R.drawable.yi5,
        sound = R.raw.xing1qi1yi1,
    ),
    Saved(
        word = "星期二",
        pinyin = "xīngqī èr",
        definition = R.string.d328,
        id1 = 328,
        stroke1 = R.drawable.xing4,
        stroke2 = R.drawable.qi5,
        stroke3 = R.drawable.er3,
        sound = R.raw.xing1qi1er4,
    ),
    Saved(
        word = "星期三",
        pinyin = "xīngqīsān",
        definition = R.string.d329,
        id1 = 329,
        stroke1 = R.drawable.xing4,
        stroke2 = R.drawable.qi5,
        stroke3 = R.drawable.san2,
        sound = R.raw.xing1qi1san1,
    ),
    Saved(
        word = "星期四",
        pinyin = "xīngqīsì",
        definition = R.string.d330,
        id1 = 330,
        stroke1 = R.drawable.xing4,
        stroke2 = R.drawable.qi5,
        stroke3 = R.drawable.si,
        sound = R.raw.xing1qi1si4,
    ),
    Saved(
        word = "星期五",
        pinyin = "xīngqīwǔ",
        definition = R.string.d331,
        id1 = 331,
        stroke1 = R.drawable.xing4,
        stroke2 = R.drawable.qi5,
        stroke3 = R.drawable.wu3,
        sound = R.raw.xing1qi1wu3,
    ),
    Saved(
        word = "星期六",
        pinyin = "xīngqīliù",
        definition = R.string.d332,
        id1 = 332,
        stroke1 = R.drawable.xing4,
        stroke2 = R.drawable.qi5,
        stroke3 = R.drawable.liu,
        sound = R.raw.xing1qi1liu4,
    ),
    Saved(
        word = "星期天",
        pinyin = "xīngqītiān",
        definition = R.string.d333,
        id1 = 333,
        stroke1 = R.drawable.xing4,
        stroke2 = R.drawable.qi5,
        stroke3 = R.drawable.tian,
        sound = R.raw.xing1qi1tian1,
    ),
    Saved(
        word = "后天",
        pinyin = "hòutiān",
        definition = R.string.d334,
        id1 = 334,
        stroke1 = R.drawable.hou,
        stroke2 = R.drawable.tian,
        sound = R.raw.hou4tian1,
    ),
    Saved(
        word = "前天",
        pinyin = "qiántiān",
        definition = R.string.d335,
        id1 = 335,
        stroke1 = R.drawable.qian2,
        stroke2 = R.drawable.tian,
        sound = R.raw.qian2tian1,
    ),
    Saved(
        word = "数学",
        pinyin = "shùxué",
        definition = R.string.d336,
        id1 = 336,
        stroke1 = R.drawable.shu5,
        stroke2 = R.drawable.xue,
        sound = R.raw.shu4xue2,
    ),
    Saved(
        word = "美术",
        pinyin = "měishù",
        definition = R.string.d337,
        id1 = 337,
        stroke1 = R.drawable.mei4,
        stroke2 = R.drawable.shu6,
        sound = R.raw.mei3shu4,
    ),
    Saved(
        word = "上午",
        pinyin = "shàngwǔ",
        definition = R.string.d338,
        id1 = 338,
        stroke1 = R.drawable.shang,
        stroke2 = R.drawable.wu,
        sound = R.raw.shang4wu3,
    ),
    Saved(
        word = "体育",
        pinyin = "tǐyù",
        definition = R.string.d339,
        id1 = 339,
        stroke1 = R.drawable.ti3,
        stroke2 = R.drawable.yu2,
        sound = R.raw.ti3yu4,
    ),

)

val vocab_lesson3: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "现在",
        pinyin = "xiànzài",
        definition = R.string.d340,
        id1 = 340,
        stroke1 = R.drawable.xian,
        stroke2 = R.drawable.zai2,
        sound = R.raw.xian4zai4,
    ),
    Saved(
        word = "点",
        pinyin = "diǎn",
        definition = R.string.d341,
        id1 = 341,
        stroke1 = R.drawable.dian4,
        sound = R.raw.dian3,
    ),
    Saved(
        word = "半",
        pinyin = "bàn",
        definition = R.string.d342,
        id1 = 342,
        stroke1 = R.drawable.ban4,
        sound = R.raw.ban4,
    ),
    Saved(
        word = "零",
        pinyin = "líng",
        definition = R.string.d343,
        id1 = 343,
        stroke1 = R.drawable.ling,
        sound = R.raw.ling2,
    ),
    Saved(
        word = "分",
        pinyin = "fēn",
        definition = R.string.d344,
        id1 = 344,
        stroke1 = R.drawable.fen,
        sound = R.raw.fen1,
    ),
    Saved(
        word = "刻",
        pinyin = "kè",
        definition = R.string.d345,
        id1 = 345,
        stroke1 = R.drawable.ke4,
        sound = R.raw.ke4,
    ),
    Saved(
        word = "差",
        pinyin = "chà",
        definition = R.string.d346,
        id1 = 346,
        stroke1 = R.drawable.cha3,
        sound = R.raw.cha4,
    ),
    Saved(
        word = "洗澡",
        pinyin = "xǐ zǎo",
        definition = R.string.d347,
        id1 = 347,
        stroke1 = R.drawable.xi6,
        stroke2 = R.drawable.zao2,
        sound = R.raw.xi3zao3,
    ),
    Saved(
        word = "睡觉",
        pinyin = "shuì jiào",
        definition = R.string.d348,
        id1 = 348,
        stroke1 = R.drawable.shui2,
        stroke2 = R.drawable.jiao6,
        sound = R.raw.shui4jiao4,
    ),
    Saved(
        word = "起床",
        pinyin = "qǐ chuáng",
        definition = R.string.d349,
        id1 = 349,
        stroke1 = R.drawable.qi2,
        stroke2 = R.drawable.chuang,
        sound = R.raw.qi3chuang2,
    ),
    Saved(
        word = "开始",
        pinyin = "kāishǐ",
        definition = R.string.d350,
        id1 = 350,
        stroke1 = R.drawable.kai,
        stroke2 = R.drawable.shi8,
        sound = R.raw.kai1shi3,
    ),

)

val vocab_lesson4: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "怎么样",
        pinyin = "zěnmeyàng",
        definition = R.string.d351,
        id1 = 351,
        stroke1 = R.drawable.zen,
        stroke2 = R.drawable.me,
        stroke3 = R.drawable.yang2,
        sound = R.raw.zen3me5yang4,
    ),
    Saved(
        word = "合适",
        pinyin = "héshì",
        definition = R.string.d352,
        id1 = 352,
        stroke1 = R.drawable.he4,
        stroke2 = R.drawable.shi9,
        sound = R.raw.he2shi4,
    ),
    Saved(
        word = "冷",
        pinyin = "lěng",
        definition = R.string.d353,
        id1 = 353,
        stroke1 = R.drawable.leng,
        sound = R.raw.leng3,
    ),
    Saved(
        word = "热",
        pinyin = "rè",
        definition = R.string.d354,
        id1 = 354,
        stroke1 = R.drawable.re,
        sound = R.raw.re4,
    ),
    Saved(
        word = "舒服",
        pinyin = "shūfu",
        definition = R.string.d355,
        id1 = 355,
        stroke1 = R.drawable.shu7,
        stroke2 = R.drawable.fu,
        sound = R.raw.shu1fu5,
    ),
    Saved(
        word = "季节",
        pinyin = "jìjié",
        definition = R.string.d356,
        id1 = 356,
        stroke1 = R.drawable.ji4,
        stroke2 = R.drawable.jie3,
        sound = R.raw.ji4jie2,
    ),
    Saved(
        word = "春天",
        pinyin = "chūntiān",
        definition = R.string.d357,
        id1 = 357,
        stroke1 = R.drawable.chun,
        stroke2 = R.drawable.tian,
        sound = R.raw.chun1tian1,
    ),
    Saved(
        word = "夏天",
        pinyin = "xiàtiān",
        definition = R.string.d358,
        id1 = 358,
        stroke1 = R.drawable.xia2,
        stroke2 = R.drawable.tian,
        sound = R.raw.xia4tian1,
    ),
    Saved(
        word = "秋天",
        pinyin = "qiūtiān",
        definition = R.string.d359,
        id1 = 359,
        stroke1 = R.drawable.qiu2,
        stroke2 = R.drawable.tian,
        sound = R.raw.qiu1tian1,
    ),
    Saved(
        word = "冬天",
        pinyin = "dōngtiān",
        definition = R.string.d360,
        id1 = 360,
        stroke1 = R.drawable.dong2,
        stroke2 = R.drawable.tian,
        sound = R.raw.dong1tian1,
    ),
    Saved(
        word = "暖和",
        pinyin = "nuǎnhuo",
        definition = R.string.d361,
        id1 = 361,
        stroke1 = R.drawable.nuan,
        stroke2 = R.drawable.he,
        sound = R.raw.nuan3huo5,
    ),
    Saved(
        word = "凉快",
        pinyin = "liángkuai",
        definition = R.string.d362,
        id1 = 362,
        stroke1 = R.drawable.liang3,
        stroke2 = R.drawable.kuai3,
        sound = R.raw.liang2kuai5,
    )
)

val vocab_lesson5: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "首都",
        pinyin = "shǒudū",
        definition = R.string.d363,
        id1 = 363,
        stroke1 = R.drawable.shou2,
        stroke2 = R.drawable.dou,
        sound = R.raw.shou3du1,
    ),
    Saved(
        word = "美丽",
        pinyin = "měilì",
        definition = R.string.d364,
        id1 = 364,
        stroke1 = R.drawable.mei4,
        stroke2 = R.drawable.li,
        sound = R.raw.mei3li4,
    ),
    Saved(
        word = "城市",
        pinyin = "chéngshì",
        definition = R.string.d365,
        id1 = 365,
        stroke1 = R.drawable.cheng2,
        stroke2 = R.drawable.shi6,
        sound = R.raw.cheng2shi4,
    ),
    Saved(
        word = "刮",
        pinyin = "guā",
        definition = R.string.d366,
        id1 = 366,
        stroke1 = R.drawable.gua2,
        sound = R.raw.gua1,
    ),
    Saved(
        word = "有时候",
        pinyin = "yǒu shíhou",
        definition = R.string.d367,
        id1 = 367,
        stroke1 = R.drawable.you4,
        stroke2 = R.drawable.shi10,
        stroke3 = R.drawable.hou3,
        sound = R.raw.you3shi2hou5,
    ),
    Saved(
        word = "下",
        pinyin = "xià",
        definition = R.string.d368,
        id1 = 368,
        stroke1 = R.drawable.xia,
        sound = R.raw.xia4,
    ),
    Saved(
        word = "雪",
        pinyin = "xuě",
        definition = R.string.d369,
        id1 = 369,
        stroke1 = R.drawable.xue2,
        sound = R.raw.xue3,
    ),
    Saved(
        word = "生日",
        pinyin = "shēngrì",
        definition = R.string.d370,
        id1 = 370,
        stroke1 = R.drawable.sheng2,
        stroke2 = R.drawable.ri,
        sound = R.raw.sheng1ri4,
    ),
    Saved(
        word = "号",
        pinyin = "hào",
        definition = R.string.d371,
        id1 = 371,
        stroke1 = R.drawable.hao2,
        sound = R.raw.hao4,
    ),
    Saved(
        word = "就",
        pinyin = "jiù",
        definition = R.string.d372,
        id1 = 372,
        stroke1 = R.drawable.jiu4,
        sound = R.raw.jiu4,
    ),
    Saved(
        word = "北京",
        pinyin = "Běijīng",
        definition = R.string.d373,
        id1 = 373,
        stroke1 = R.drawable.bei2,
        stroke2 = R.drawable.jing4,
        sound = R.raw.bei3jing1,
    ),
)

val vocab_lesson6: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "书法",
        pinyin = "shūfǎ",
        definition = R.string.d374,
        id1 = 374,
        stroke1 = R.drawable.shu,
        stroke2 = R.drawable.fa2,
        sound = R.raw.shu1fa3,
    ),
    Saved(
        word = "功夫",
        pinyin = "gōngfu",
        definition = R.string.d375,
        id1 = 375,
        stroke1 = R.drawable.gong2,
        stroke2 = R.drawable.fu2,
        sound = R.raw.gong1fu5,
    ),
    Saved(
        word = "上网",
        pinyin = "shàng wǎng",
        definition = R.string.d376,
        id1 = 376,
        stroke1 = R.drawable.shang,
        stroke2 = R.drawable.wang2,
        sound = R.raw.shang4wang3,
    ),
    Saved(
        word = "还",
        pinyin = "hái",
        definition = R.string.d377,
        id1 = 377,
        stroke1 = R.drawable.hai,
        sound = R.raw.hai2,
    ),
    Saved(
        word = "箱子",
        pinyin = "xiāngzi",
        definition = R.string.d378,
        id1 = 378,
        stroke1 = R.drawable.xiang,
        stroke2 = R.drawable.zi2,
        sound = R.raw.xiang1zi5,
    ),
    Saved(
        word = "日用品",
        pinyin = "rìyòngpǐn",
        definition = R.string.d379,
        id1 = 379,
        stroke1 = R.drawable.ri,
        stroke2 = R.drawable.yong,
        stroke3 = R.drawable.pin,
        sound = R.raw.ri4yong4pin3,
    ),
    Saved(
        word = "甜",
        pinyin = "tián",
        definition = R.string.d380,
        id1 = 380,
        stroke1 = R.drawable.tian2,
        sound = R.raw.tian2,
    ),
    Saved(
        word = "酸",
        pinyin = "suān",
        definition = R.string.d381,
        id1 = 381,
        stroke1 = R.drawable.suan,
        sound = R.raw.suan1,
    ),
    Saved(
        word = "音乐",
        pinyin = "yīnyuè",
        definition = R.string.d382,
        id1 = 382,
        stroke1 = R.drawable.yin3,
        stroke2 = R.drawable.le2,
        sound = R.raw.yin1yue4,
    ),
    Saved(
        word = "生词",
        pinyin = "shēngcí",
        definition = R.string.d383,
        id1 = 383,
        stroke1 = R.drawable.sheng2,
        stroke2 = R.drawable.ci,
        sound = R.raw.sheng1ci2,
    ),
    Saved(
        word = "句子",
        pinyin = "jùzi",
        definition = R.string.d384,
        id1 = 384,
        stroke1 = R.drawable.ju4,
        stroke2 = R.drawable.zi2,
        sound = R.raw.ju4zi5,
    ),
    Saved(
        word = "课文",
        pinyin = "kèwén",
        definition = R.string.d385,
        id1 = 385,
        stroke1 = R.drawable.ke2,
        stroke2 = R.drawable.wen2,
        sound = R.raw.ke4wen2,
    ),
    Saved(
        word = "大家",
        pinyin = "dàjiā",
        definition = R.string.d386,
        id1 = 386,
        stroke1 = R.drawable.da3,
        stroke2 = R.drawable.jia2,
        sound = R.raw.da4jia1,
    ),
    Saved(
        word = "开心",
        pinyin = "kāixīn",
        definition = R.string.d387,
        id1 = 387,
        stroke1 = R.drawable.kai,
        stroke2 = R.drawable.xin2,
        sound = R.raw.kai1xin1,
    ),
)

val vocab_lesson7: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "给",
        pinyin = "gěi",
        definition = R.string.d388,
        id1 = 388,
        stroke1 = R.drawable.gei,
        sound = R.raw.gei3,
    ),
    Saved(
        word = "礼物",
        pinyin = "lǐwù",
        definition = R.string.d389,
        id1 = 389,
        stroke1 = R.drawable.li5,
        stroke2 = R.drawable.wu2,
        sound = R.raw.li3wu4,
    ),
    Saved(
        word = "束",
        pinyin = "shù",
        definition = R.string.d390,
        id1 = 390,
        stroke1 = R.drawable.shu4,
        sound = R.raw.shu4,
    ),
    Saved(
        word = "鲜花",
        pinyin = "xiānhuā",
        definition = R.string.d391,
        id1 = 391,
        stroke1 = R.drawable.xian2,
        stroke2 = R.drawable.hua4,
        sound = R.raw.xian1hua1,
    ),
    Saved(
        word = "问题",
        pinyin = "wèntí",
        definition = R.string.d392,
        id1 = 392,
        stroke1 = R.drawable.wen,
        stroke2 = R.drawable.ti2,
        sound = R.raw.wen4ti2,
    ),
    Saved(
        word = "告诉",
        pinyin = "gàosu",
        definition = R.string.d393,
        id1 = 393,
        stroke1 = R.drawable.gao2,
        stroke2 = R.drawable.su,
        sound = R.raw.gao4su5,
    ),
    Saved(
        word = "秘密",
        pinyin = "mìmì",
        definition = R.string.d394,
        id1 = 394,
        stroke1 = R.drawable.mi2,
        stroke2 = R.drawable.mi3,
        sound = R.raw.mi4mi4,
    ),
    Saved(
        word = "姑姑",
        pinyin = "gūgu",
        definition = R.string.d395,
        id1 = 395,
        stroke1 = R.drawable.gu,
        sound = R.raw.gu1gu5,
    ),
    Saved(
        word = "事情",
        pinyin = "shìqing",
        definition = R.string.d396,
        id1 = 396,
        stroke1 = R.drawable.shi11,
        stroke2 = R.drawable.qing2,
        sound = R.raw.shi4qing2,
    ),
    Saved(
        word = "封",
        pinyin = "fēng",
        definition = R.string.d397,
        id1 = 397,
        stroke1 = R.drawable.feng2,
        sound = R.raw.feng1,
    ),
    Saved(
        word = "信",
        pinyin = "xìn",
        definition = R.string.d398,
        id1 = 398,
        stroke1 = R.drawable.xin3,
        sound = R.raw.xin4,
    ),
    Saved(
        word = "您",
        pinyin = "nín",
        definition = R.string.d399,
        id1 = 399,
        stroke1 = R.drawable.nin,
        sound = R.raw.nin2,
    ),
)

val vocab_lesson8: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "请",
        pinyin = "qǐng",
        definition = R.string.d400,
        id1 = 400,
        stroke1 = R.drawable.qing3,
        sound = R.raw.qing3,
    ),
    Saved(
        word = "菜",
        pinyin = "cài",
        definition = R.string.d401,
        id1 = 401,
        stroke1 = R.drawable.cai,
        sound = R.raw.cai4,
    ),
    Saved(
        word = "唱",
        pinyin = "chàng",
        definition = R.string.d402,
        id1 = 402,
        stroke1 = R.drawable.chang4,
        sound = R.raw.chang4,
    ),
    Saved(
        word = "杂技",
        pinyin = "zájì",
        definition = R.string.d403,
        id1 = 403,
        stroke1 = R.drawable.za,
        stroke2 = R.drawable.ji5,
        sound = R.raw.za2ji4,
    ),
    Saved(
        word = "让",
        pinyin = "ràng",
        definition = R.string.d404,
        id1 = 404,
        stroke1 = R.drawable.rang,
        sound = R.raw.rang4,
    ),
    Saved(
        word = "洗",
        pinyin = "xǐ",
        definition = R.string.d405,
        id1 = 405,
        stroke1 = R.drawable.xi6,
        sound = R.raw.xi3,
    ),
    Saved(
        word = "袜子",
        pinyin = "wàzi",
        definition = R.string.d406,
        id1 = 406,
        stroke1 = R.drawable.wa,
        stroke2 = R.drawable.zi2,
        sound = R.raw.wa4zi5,
    ),
    Saved(
        word = "祝",
        pinyin = "zhù",
        definition = R.string.d407,
        id1 = 407,
        stroke1 = R.drawable.zhu,
        sound = R.raw.zhu4,
    ),
    Saved(
        word = "快乐",
        pinyin = "kuàilè",
        definition = R.string.d408,
        id1 = 408,
        stroke1 = R.drawable.kuai3,
        stroke2 = R.drawable.le2,
        sound = R.raw.kuai4le4,
    ),
    Saved(
        word = "新年",
        pinyin = "xīnnián",
        definition = R.string.d409,
        id1 = 409,
        stroke1 = R.drawable.xin,
        stroke2 = R.drawable.nian,
        sound = R.raw.xin1nian2,
    ),
    Saved(
        word = "过",
        pinyin = "guò",
        definition = R.string.d410,
        id1 = 410,
        stroke1 = R.drawable.guo3,
        sound = R.raw.guo4,
    ),
    Saved(
        word = "送",
        pinyin = "sòng",
        definition = R.string.d411,
        id1 = 411,
        stroke1 = R.drawable.song,
        sound = R.raw.song4,
    ),
    Saved(
        word = "茶叶",
        pinyin = "cháyè",
        definition = R.string.d412,
        id1 = 412,
        stroke1 = R.drawable.cha2,
        stroke2 = R.drawable.ye4,
        sound = R.raw.cha2ye4,
    ),
    Saved(
        word = "围巾",
        pinyin = "wéijīn",
        definition = R.string.d413,
        id1 = 413,
        stroke1 = R.drawable.wei,
        stroke2 = R.drawable.jin3,
        sound = R.raw.wei2jin1,
    ),
    Saved(
        word = "中秋节",
        pinyin = "Zhōngqiū Jié",
        definition = R.string.d414,
        id1 = 414,
        stroke1 = R.drawable.zhong,
        stroke2 = R.drawable.qiu2,
        stroke3 = R.drawable.jie3,
        sound = R.raw.zhong1qiu1jie2,
    )
)

val vocab_lesson9: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "电影",
        pinyin = "diànyǐng",
        definition = R.string.d415,
        id1 = 415,
        stroke1 = R.drawable.dian2,
        stroke2 = R.drawable.ying,
        sound = R.raw.dian4ying3,
    ),
    Saved(
        word = "京剧",
        pinyin = "jīngjù",
        definition = R.string.d416,
        id1 = 416,
        stroke1 = R.drawable.jing4,
        stroke2 = R.drawable.ju5,
        sound = R.raw.jing1ju4,
    ),
    Saved(
        word = "糖",
        pinyin = "táng",
        definition = R.string.d417,
        id1 = 417,
        stroke1 = R.drawable.tang2,
        sound = R.raw.tang2,
    ),
    Saved(
        word = "画",
        pinyin = "huà",
        definition = R.string.d418,
        id1 = 418,
        stroke1 = R.drawable.hua3,
        sound = R.raw.hua4,
    ),
    Saved(
        word = "画儿",
        pinyin = "huàr",
        definition = R.string.d419,
        id1 = 419,
        stroke1 = R.drawable.hua3,
        stroke2 = R.drawable.er,
        sound = R.raw.huar4,
    ),
    Saved(
        word = "可乐",
        pinyin = "kělè",
        definition = R.string.d420,
        id1 = 420,
        stroke1 = R.drawable.ke3,
        stroke2 = R.drawable.le2,
        sound = R.raw.ke3le4,
    ),
    Saved(
        word = "特别",
        pinyin = "tèbié",
        definition = R.string.d421,
        id1 = 421,
        stroke1 = R.drawable.te,
        stroke2 = R.drawable.bie,
        sound = R.raw.te4bie2,
    ),
    Saved(
        word = "电影院",
        pinyin = "diànyǐngyuàn",
        definition = R.string.d422,
        id1 = 422,
        stroke1 = R.drawable.dian2,
        stroke2 = R.drawable.ying,
        stroke3 = R.drawable.yuan2,
        sound = R.raw.dian4ying3yuan4,
    ),
    Saved(
        word = "演",
        pinyin = "yǎn",
        definition = R.string.d423,
        id1 = 423,
        stroke1 = R.drawable.yan3,
        sound = R.raw.yan3,
    ),
    Saved(
        word = "听说",
        pinyin = "tīngshuō",
        definition = R.string.d424,
        id1 = 424,
        stroke1 = R.drawable.ting,
        stroke2 = R.drawable.shuo,
        sound = R.raw.ting1shuo1,
    ),
    Saved(
        word = "有意思",
        pinyin = "yǒu yìsi",
        definition = R.string.d425,
        id1 = 425,
        stroke1 = R.drawable.you4,
        stroke2 = R.drawable.yi6,
        stroke3 = R.drawable.si2,
        sound = R.raw.you3yi4si5,
    ),
    Saved(
        word = "打算",
        pinyin = "dǎsuàn",
        definition = R.string.d426,
        id1 = 426,
        stroke1 = R.drawable.da,
        stroke2 = R.drawable.suan2,
        sound = R.raw.da3suan4,
    )
)

val vocab_lesson10: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "兔子",
        pinyin = "tùzi",
        definition = R.string.d427,
        id1 = 427,
        stroke1 = R.drawable.tu2,
        stroke2 = R.drawable.zi2,
        sound = R.raw.tu4zi5,
    ),
    Saved(
        word = "山羊",
        pinyin = "shānyáng",
        definition = R.string.d428,
        id1 = 428,
        stroke1 = R.drawable.shan,
        stroke2 = R.drawable.yang3,
        sound = R.raw.shan1yang2,
    ),
    Saved(
        word = "鱼",
        pinyin = "yú",
        definition = R.string.d429,
        id1 = 429,
        stroke1 = R.drawable.yu3,
        sound = R.raw.yu2,
    ),
    Saved(
        word = "准备",
        pinyin = "zhǔnbèi",
        definition = R.string.d430,
        id1 = 430,
        stroke1 = R.drawable.zhun,
        stroke2 = R.drawable.bei3,
        sound = R.raw.zhun3bei4,
    ),
    Saved(
        word = "胡萝卜",
        pinyin = "húluóbo",
        definition = R.string.d431,
        id1 = 431,
        stroke1 = R.drawable.hu2,
        stroke2 = R.drawable.luo,
        stroke3 = R.drawable.bo,
        sound = R.raw.hu2luo2bo5,
    ),
    Saved(
        word = "篮",
        pinyin = "lán",
        definition = R.string.d432,
        id1 = 432,
        stroke1 = R.drawable.lan,
        sound = R.raw.lan2,
    ),
    Saved(
        word = "青菜",
        pinyin = "qīngcài",
        definition = R.string.d433,
        id1 = 433,
        stroke1 = R.drawable.qing4,
        stroke2 = R.drawable.cai,
        sound = R.raw.qing1cai4,
    ),
    Saved(
        word = "来",
        pinyin = "lái",
        definition = R.string.d434,
        id1 = 434,
        stroke1 = R.drawable.lai,
        sound = R.raw.lai2,
    )
)

val vocab_lesson11: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "海",
        pinyin = "hǎi",
        definition = R.string.d435,
        id1 = 435,
        stroke1 = R.drawable.hai2,
        sound = R.raw.hai3,
    ),
    Saved(
        word = "玩",
        pinyin = "wán",
        definition = R.string.d436,
        id1 = 436,
        stroke1 = R.drawable.wan2,
        sound = R.raw.wan2,
    ),
    Saved(
        word = "沙子",
        pinyin = "shāzi",
        definition = R.string.d437,
        id1 = 437,
        stroke1 = R.drawable.sha,
        stroke2 = R.drawable.zi2,
        sound = R.raw.sha1zi5,
    ),
    Saved(
        word = "工作",
        pinyin = "gōngzuò",
        definition = R.string.d438,
        id1 = 438,
        stroke1 = R.drawable.gong3,
        stroke2 = R.drawable.zuo,
        sound = R.raw.gong1zuo4,
    ),
    Saved(
        word = "极了",
        pinyin = "jíle",
        definition = R.string.d439,
        id1 = 439,
        stroke1 = R.drawable.ji6,
        stroke2 = R.drawable.le,
        sound = R.raw.ji2le5,
    ),
    Saved(
        word = "幅",
        pinyin = "fú",
        definition = R.string.d440,
        id1 = 440,
        stroke1 = R.drawable.fu3,
        sound = R.raw.fu2,
    ),
    Saved(
        word = "公司",
        pinyin = "gōngsī",
        definition = R.string.d441,
        id1 = 441,
        stroke1 = R.drawable.gong,
        stroke2 = R.drawable.si3,
        sound = R.raw.gong1si1,
    ),
    Saved(
        word = "上班",
        pinyin = "shàng bān",
        definition = R.string.d442,
        id1 = 442,
        stroke1 = R.drawable.shang,
        stroke2 = R.drawable.ban3,
        sound = R.raw.shang4ban1,
    ),
    Saved(
        word = "全",
        pinyin = "quán",
        definition = R.string.d443,
        id1 = 443,
        stroke1 = R.drawable.quan,
        sound = R.raw.quan2,
    ),
    Saved(
        word = "风景",
        pinyin = "fēngjǐng",
        definition = R.string.d444,
        id1 = 444,
        stroke1 = R.drawable.feng,
        stroke2 = R.drawable.jing5,
        sound = R.raw.feng1jing3,
    ),
    Saved(
        word = "美",
        pinyin = "měi",
        definition = R.string.d445,
        id1 = 445,
        stroke1 = R.drawable.mei4,
        sound = R.raw.mei3,
    ),
    Saved(
        word = "游泳",
        pinyin = "yóu yǒng",
        definition = R.string.d446,
        id1 = 446,
        stroke1 = R.drawable.you3,
        stroke2 = R.drawable.yong2,
        sound = R.raw.you2yong3,
    ),
    Saved(
        word = "晒",
        pinyin = "shài",
        definition = R.string.d447,
        id1 = 447,
        stroke1 = R.drawable.shai,
        sound = R.raw.shai4,
    ),
    Saved(
        word = "太阳",
        pinyin = "tàiyáng",
        definition = R.string.d448,
        id1 = 448,
        stroke1 = R.drawable.tai2,
        stroke2 = R.drawable.yang4,
        sound = R.raw.tai4yang2,
    )
)

val vocab_lesson12: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "外婆",
        pinyin = "wàipó",
        definition = R.string.d449,
        id1 = 449,
        stroke1 = R.drawable.wai,
        stroke2 = R.drawable.po,
        sound = R.raw.wai4po2,
    ),
    Saved(
        word = "外公",
        pinyin = "wàigōng",
        definition = R.string.d450,
        id1 = 450,
        stroke1 = R.drawable.wai,
        stroke2 = R.drawable.gong,
        sound = R.raw.wai4gong1,
    ),
    Saved(
        word = "故事",
        pinyin = "gùshi",
        definition = R.string.d451,
        id1 = 451,
        stroke1 = R.drawable.gu2,
        stroke2 = R.drawable.shi11,
        sound = R.raw.gu4shi5,
    ),
    Saved(
        word = "跟",
        pinyin = "gēn",
        definition = R.string.d452,
        id1 = 452,
        stroke1 = R.drawable.gen,
        sound = R.raw.gen1,
    ),
    Saved(
        word = "商店",
        pinyin = "shāngdiàn",
        definition = R.string.d453,
        id1 = 453,
        stroke1 = R.drawable.shang2,
        stroke2 = R.drawable.dian5,
        sound = R.raw.shang1dian4,
    ),
    Saved(
        word = "植物园",
        pinyin = "zhíwùyuán",
        definition = R.string.d454,
        id1 = 454,
        stroke1 = R.drawable.zhi4,
        stroke2 = R.drawable.wu2,
        stroke3 = R.drawable.yuan3,
        sound = R.raw.zhi2wu4yuan2,
    ),
    Saved(
        word = "下棋",
        pinyin = "xià qí",
        definition = R.string.d455,
        id1 = 455,
        stroke1 = R.drawable.xia,
        stroke2 = R.drawable.qi6,
        sound = R.raw.xia4qi2,
    ),
    Saved(
        word = "敢",
        pinyin = "gǎn",
        definition = R.string.d456,
        id1 = 456,
        stroke1 = R.drawable.gan2,
        sound = R.raw.gan3,
    ),
    Saved(
        word = "自己",
        pinyin = "zìjǐ",
        definition = R.string.d457,
        id1 = 457,
        stroke1 = R.drawable.zi,
        stroke2 = R.drawable.ji7,
        sound = R.raw.zi4ji3,
    ),
    Saved(
        word = "勇敢",
        pinyin = "yǒnggǎn",
        definition = R.string.d458,
        id1 = 458,
        stroke1 = R.drawable.yong3,
        stroke2 = R.drawable.gan2,
        sound = R.raw.yong3gan3,
    ),
    Saved(
        word = "孩子",
        pinyin = "háizi",
        definition = R.string.d459,
        id1 = 459,
        stroke1 = R.drawable.hai3,
        stroke2 = R.drawable.zi2,
        sound = R.raw.hai2zi5,
    ),
    Saved(
        word = "已经",
        pinyin = "yǐjīng",
        definition = R.string.d460,
        id1 = 460,
        stroke1 = R.drawable.yi7,
        stroke2 = R.drawable.jing6,
        sound = R.raw.yi3jing1,
    ),
    Saved(
        word = "长大",
        pinyin = "zhǎngdà",
        definition = R.string.d461,
        id1 = 461,
        stroke1 = R.drawable.chang2,
        stroke2 = R.drawable.da3,
        sound = R.raw.zhang3da4,
    )
)

val vocab_lesson13: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "太极拳",
        pinyin = "tàijíquán",
        definition = R.string.d462,
        id1 = 462,
        stroke1 = R.drawable.tai2,
        stroke2 = R.drawable.ji6,
        stroke3 = R.drawable.quan2,
        sound = R.raw.tai4ji2quan2,
    ),
    Saved(
        word = "熊猫",
        pinyin = "xióngmāo",
        definition = R.string.d463,
        id1 = 463,
        stroke1 = R.drawable.xiong,
        stroke2 = R.drawable.mao2,
        sound = R.raw.xiong2mao1,
    ),
    Saved(
        word = "买",
        pinyin = "mǎi",
        definition = R.string.d464,
        id1 = 464,
        stroke1 = R.drawable.mai,
        sound = R.raw.mai3,
    ),
    Saved(
        word = "东西",
        pinyin = "dōngxi",
        definition = R.string.d465,
        id1 = 465,
        stroke1 = R.drawable.dong3,
        stroke2 = R.drawable.xi3,
        sound = R.raw.dong1xi5,
    ),
    Saved(
        word = "接",
        pinyin = "jiē",
        definition = R.string.d466,
        id1 = 466,
        stroke1 = R.drawable.jie4,
        sound = R.raw.jie1,
    ),
    Saved(
        word = "到",
        pinyin = "dào",
        definition = R.string.d467,
        id1 = 467,
        stroke1 = R.drawable.dao2,
        sound = R.raw.dao4,
    ),
    Saved(
        word = "取",
        pinyin = "qǔ",
        definition = R.string.d468,
        id1 = 468,
        stroke1 = R.drawable.qu2,
        sound = R.raw.qu3,
    ),
    Saved(
        word = "包裹",
        pinyin = "bāoguǒ",
        definition = R.string.d469,
        id1 = 469,
        stroke1 = R.drawable.bao,
        stroke2 = R.drawable.guo4,
        sound = R.raw.bao1guo3,
    ),
    Saved(
        word = "找",
        pinyin = "zhǎo",
        definition = R.string.d470,
        id1 = 470,
        stroke1 = R.drawable.zhao2,
        sound = R.raw.zhao3,
    ),
    Saved(
        word = "拿",
        pinyin = "ná",
        definition = R.string.d471,
        id1 = 471,
        stroke1 = R.drawable.na4,
        sound = R.raw.na2,
    ),
    Saved(
        word = "钥匙",
        pinyin = "yàoshi",
        definition = R.string.d472,
        id1 = 472,
        stroke1 = R.drawable.yao,
        stroke2 = R.drawable.shi12,
        sound = R.raw.yao4shi5,
    ),
    Saved(
        word = "换",
        pinyin = "huàn",
        definition = R.string.d473,
        id1 = 473,
        stroke1 = R.drawable.huan2,
        sound = R.raw.huan4,
    ),
    Saved(
        word = "跑步",
        pinyin = "pǎo bù",
        definition = R.string.d474,
        id1 = 474,
        stroke1 = R.drawable.pao,
        stroke2 = R.drawable.bu3,
        sound = R.raw.pao3bu4,
    ),
    Saved(
        word = "健康",
        pinyin = "jiànkāng",
        definition = R.string.d475,
        id1 = 475,
        stroke1 = R.drawable.jian4,
        stroke2 = R.drawable.kang,
        sound = R.raw.jian4kang1,
    )
)

val vocab_lesson14: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "车",
        pinyin = "chē",
        definition = R.string.d476,
        id1 = 476,
        stroke1 = R.drawable.che,
        sound = R.raw.che1,
    ),
    Saved(
        word = "火车",
        pinyin = "huǒchē",
        definition = R.string.d477,
        id1 = 477,
        stroke1 = R.drawable.huo,
        stroke2 = R.drawable.che,
        sound = R.raw.huo3che1,
    ),
    Saved(
        word = "飞机",
        pinyin = "fēijī",
        definition = R.string.d478,
        id1 = 478,
        stroke1 = R.drawable.fei2,
        stroke2 = R.drawable.ji8,
        sound = R.raw.fei1ji1,
    ),
    Saved(
        word = "手机",
        pinyin = "shǒujī",
        definition = R.string.d479,
        id1 = 479,
        stroke1 = R.drawable.shou,
        stroke2 = R.drawable.ji8,
        sound = R.raw.shou3ji1,
    ),
    Saved(
        word = "帮",
        pinyin = "bāng",
        definition = R.string.d480,
        id1 = 480,
        stroke1 = R.drawable.bang,
        sound = R.raw.bang1,
    ),
    Saved(
        word = "擦",
        pinyin = "cā",
        definition = R.string.d481,
        id1 = 481,
        stroke1 = R.drawable.ca,
        sound = R.raw.ca1,
    ),
    Saved(
        word = "种",
        pinyin = "zhǒng",
        definition = R.string.d482,
        id1 = 482,
        stroke1 = R.drawable.zhong2,
        sound = R.raw.zhong3,
    ),
    Saved(
        word = "老虎",
        pinyin = "lǎohǔ",
        definition = R.string.d483,
        id1 = 483,
        stroke1 = R.drawable.lao,
        stroke2 = R.drawable.hu3,
        sound = R.raw.lao3hu3,
    ),
    Saved(
        word = "脸",
        pinyin = "liǎn",
        definition = R.string.d484,
        id1 = 484,
        stroke1 = R.drawable.lian2,
        sound = R.raw.lian3,
    ),
    Saved(
        word = "大象",
        pinyin = "dàxiàng",
        definition = R.string.d485,
        id1 = 485,
        stroke1 = R.drawable.da3,
        stroke2 = R.drawable.xiang4,
        sound = R.raw.da4xiang4,
    ),
    Saved(
        word = "吸",
        pinyin = "xī",
        definition = R.string.d486,
        id1 = 486,
        stroke1 = R.drawable.xi7,
        sound = R.raw.xi1,
    ),
    Saved(
        word = "水",
        pinyin = "shuǐ",
        definition = R.string.d487,
        id1 = 487,
        stroke1 = R.drawable.shui,
        sound = R.raw.shui3,
    ),
    Saved(
        word = "草地",
        pinyin = "cǎodì",
        definition = R.string.d488,
        id1 = 488,
        stroke1 = R.drawable.cao2,
        stroke2 = R.drawable.di2,
        sound = R.raw.cao3di4,
    ),
    Saved(
        word = "竹子",
        pinyin = "zhúzi",
        definition = R.string.d489,
        id1 = 489,
        stroke1 = R.drawable.zhu2,
        stroke2 = R.drawable.zi2,
        sound = R.raw.zhu2zi5,
    ),
    Saved(
        word = "香港",
        pinyin = "Xiānggǎng",
        definition = R.string.d490,
        id1 = 490,
        stroke1 = R.drawable.xiang3,
        stroke2 = R.drawable.gang,
        sound = R.raw.xiang1gang3,
    )
)

val vocab_lesson15: ArrayList<Saved> = arrayListOf(

    Saved(
        word = "郊游",
        pinyin = "jiāoyóu",
        definition = R.string.d491,
        id1 = 491,
        stroke1 = R.drawable.jiao7,
        stroke2 = R.drawable.you3,
        sound = R.raw.jiao1you2,
    ),
    Saved(
        word = "晴朗",
        pinyin = "qínglǎng",
        definition = R.string.d492,
        id1 = 492,
        stroke1 = R.drawable.qing5,
        stroke2 = R.drawable.lang,
        sound = R.raw.qing2lang3,
    ),
    Saved(
        word = "组织",
        pinyin = "zǔzhī",
        definition = R.string.d493,
        id1 = 493,
        stroke1 = R.drawable.zu2,
        stroke2 = R.drawable.zhi5,
        sound = R.raw.zu3zhi1,
    ),
    Saved(
        word = "郊外",
        pinyin = "jiāowài",
        definition = R.string.d494,
        id1 = 494,
        stroke1 = R.drawable.jiao7,
        stroke2 = R.drawable.wai,
        sound = R.raw.jiao1wai4,
    ),
    Saved(
        word = "放",
        pinyin = "fàng",
        definition = R.string.d495,
        id1 = 495,
        stroke1 = R.drawable.fang2,
        sound = R.raw.fang4,
    ),
    Saved(
        word = "风筝",
        pinyin = "fēngzheng",
        definition = R.string.d496,
        id1 = 496,
        stroke1 = R.drawable.feng,
        stroke2 = R.drawable.zheng,
        sound = R.raw.feng1zheng1,
    ),
    Saved(
        word = "跳舞",
        pinyin = "tiào wǔ",
        definition = R.string.d497,
        id1 = 497,
        stroke1 = R.drawable.tiao,
        stroke2 = R.drawable.wu5,
        sound = R.raw.tiao4wu3,
    ),
    Saved(
        word = "捉迷藏",
        pinyin = "zhuōmícáng",
        definition = R.string.d498,
        id1 = 498,
        stroke1 = R.drawable.zhuo2,
        stroke2 = R.drawable.mi4,
        stroke3 = R.drawable.cang,
        sound = R.raw.zhuo1mi2cang2,
    )
)


val vocabAll: List<Saved> = vocab_lesson1 + vocab_lesson2 + vocab_lesson3 + vocab_lesson4 +
        vocab_lesson5 + vocab_lesson6 + vocab_lesson7 + vocab_lesson8 +
        vocab_lesson9 + vocab_lesson10 + vocab_lesson11 + vocab_lesson12 +
        vocab_lesson13 + vocab_lesson14 + vocab_lesson15




